### ISSUE TITLE
livecd-creator crashes on EL 8.6 with "leaked a reference to the filesystem" error

### ISSUE THREAD

**Issue by dowdle** [livecd-tools/livecd-tools#232] opened 2022-05-12 04:10 UTC
Just updated to AlmaLinux 8.6 and have livecd-tools-30.0-1.el8.x86_64 installed.  Tried to do a build a few times with livecd-creator and it kept crashing with the following error:

Error creating Live CD : Unable to unmount filesystem at /var/tmp/imgcreate-e84ozsji/install_root/var/cache/dnf. The process using the imgcreate module, or one of the libraries used by that process, leaked a reference to the filesystem. Please report a bug at <https://github.com/livecd-tools/livecd-tools/issues>.
umount: /var/tmp/imgcreate-e84ozsji/install_root/sys/fs/selinux/load: not mounted.
Traceback (most recent call last):
  File "/usr/bin/livecd-creator", line 265, in <module>
    sys.exit(main())
  File "/usr/bin/livecd-creator", line 252, in main
    creator.cleanup()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 613, in cleanup
    self.unmount()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 585, in unmount
    self._undo_bindmounts()
  File "/usr/lib/python3.6/site-packages/imgcreate/creator.py", line 355, in _undo_bindmounts
    b.unmount()
  File "/usr/lib/python3.6/site-packages/imgcreate/fs.py", line 1063, in unmount
    raise MountError(umount_fail_fmt % self.dest)

**Comment by Conan-Kudo** [comment] 2022-05-14 20:08
@rwmjones @lersek Could you take a look at this?

**Comment by rwmjones** [comment] 2022-05-14 21:01
It's almost certainly caused by the recent change in https://github.com/livecd-tools/livecd-tools/commit/9095966dd092562c4f4c5d56cc9354583ef3a699

However, reporter, there's no information here about how to reproduce this.  You tried to build what?

**Comment by dowdle** [comment] 2022-05-14 21:08
I was building AlmaLinux 8.6 on AlmaLinux 8.6 of course.
The kickstarts are here:
http://img.cs.montana.edu/linux/montanalinux/config/a8/

I've pretty much used the same kickstarts during the 8.4 series and the 8.5 series... and it worked fine in March when I last built 8.5.  At that time though, I was using livemedia-creator (for Fedora 35/36 and EL8) but have since switched to livecd-creator since it was fixed recently.

**Comment by rwmjones** [comment] 2022-05-14 21:48
Can you try seeing what is holding on to resources during the build?  You'll have to add either `fuser` or `lsof` to the package list and run the command right at the end of the `%post` script.

Note that we're just demonstrating that previously you had an incomplete, in some cases potentially corrupt filesystem in the final live CD.

**Comment by lersek** [comment] 2022-05-16 08:01
> Can you try seeing what is holding on to resources during the build? You'll have to add either `fuser` or `lsof` to the package list and run the command right at the end of the `%post` script.
> 
> Note that we're just demonstrating that previously you had an incomplete, in some cases potentially corrupt filesystem in the final live CD.

I agree. As far as I can tell, commit 9095966dd092 is working as intended: it is now catching the DNF bug. This is the key message:

> Unable to unmount filesystem at /var/tmp/imgcreate-e84ozsji/install_root/var/cache/dnf

That is the filesystem under which the libsolv file descriptors are leaked.

@dowdle please file a ticket at https://bugzilla.redhat.com, for the DNF component, and the RHEL-8 product, for backporting upstream commit https://github.com/rpm-software-management/dnf/commit/5ce5ed1ea08a. Thanks!

**Comment by dowdle** [comment] 2022-05-17 16:43
Greetings,

----- Original Message -----
> Can you try seeing what is holding on to resources during the build?
> You'll have to add either fuser or lsof to the package list and run
> the command right at the end of the %post script.

I tried that (with lsof [I don't know how to use fuser]) and it output 2,000+ lines (over my default tmux buffer)... which a ton of stuff being on the host.

TYL,
-- 
Scott Dowdle
704 Church Street
Belgrade, MT 59714
(406)388-0827 [home]
(406)994-3931 [work]

**Comment by rwmjones** [comment] 2022-05-17 17:58
Try updating dnf to one containing the fix that Laszlo mentioned above.

**Comment by dowdle** [comment] 2022-05-17 19:41
Greetings,

----- Original Message -----
> Try updating dnf to one containing the fix that Laszlo mentioned above.

The changes made to /usr/lib/python3.6/site-packages/imgcreate/fs.py appear to have already been made in the released livecd-tools-30.0-1.el8.x86_64 package.

TYL,
-- 
Scott Dowdle
704 Church Street
Belgrade, MT 59714
(406)388-0827 [home]
(406)994-3931 [work]

**Comment by lersek** [comment] 2022-05-18 10:11
@dowdle We're discussing two different packages here; `livecd-tools` and `dnf`. The direct error message you've encountered comes from `livecd-tools`, but as the message says, it catches an issue caused **by some other package** on the system:

> The process using the imgcreate module, or **one of the libraries used by that process**, leaked a reference to the filesystem

Normally, which package causes the actual problem needs to be determined by the user (hopefully with the help of the `livecd-tools` developers). However, in this particular case, I recognized the problematic filesystem path in the error report, and I told you immediately which package the culprit was. The culprit (sub)package is `python3-dnf`, which comes from the `dnf` SRPM.

`livecd-creator` uses the python-language DNF library, and that library (very indirectly) has a bug, which in turn causes `livecd-creator` to mis-build the ISO image. `livecd-creator` can now catch this problem when the `umount` command fails, but it cannot fix or mitigate it. For fixing the actual problem, the upstream DNF fix I mentioned above, namely https://github.com/rpm-software-management/dnf/commit/5ce5ed1ea08a, needs to be backported to RHEL-8 (and consequently to AlmaLinux). That's why I suggested that you please report a DNF bug in the RH Bugzilla, and aks for this upstream DNF fix to be backported to RHEL-8.

Once you update the DNF packages on your system, including `python3-dnf`, to a version that contains a backport of the upstream DNF fix, then your *current* `livecd-tools` package will start working.

**Comment by Conan-Kudo** [comment] 2022-05-18 11:20
Hopefully @lersek and @rwmjones could help make this a z-stream fix for RHEL 8.6, because it's pretty aggravating.

**Comment by Conan-Kudo** [comment] 2022-05-18 11:28
Bug filed: https://bugzilla.redhat.com/show_bug.cgi?id=2087734

**Comment by dowdle** [comment] 2022-10-11 07:37
Greetings,

----- Original Message -----
> @dowdle We're discussing two different packages here; livecd-tools
> and dnf . The direct error message you've encountered comes from
> livecd-tools , but as the message says, it catches an issue caused
> by some other package on the system:
> 
> The process using the imgcreate module, or one of the libraries used
> by that process , leaked a reference to the filesystem
> 
> Normally, which package causes the actual problem needs to be
> determined by the user (hopefully with the help of the livecd-tools
> developers). However, in this particular case, I recognized the
> problematic filesystem path in the error report, and I told you
> immediately which package the culprit was. The culprit (sub)package
> is python3-dnf , which comes from the dnf SRPM.
> 
> livecd-creator uses the python-language DNF library, and that library
> (very indirectly) has a bug, which in turn causes livecd-creator to
> mis-build the ISO image. livecd-creator can now catch this problem
> when the umount command fails, but it cannot fix or mitigate it. For
> fixing the actual problem, the upstream DNF fix I mentioned above,
> namely rpm-software-management/dnf@ 5ce5ed1ea08a , needs to be
> backported to RHEL-8 (and consequently to AlmaLinux). That's why I
> suggested that you please report a DNF bug in the RH Bugzilla, and
> aks for this upstream DNF fix to be backported to RHEL-8.
> 
> Once you update the DNF packages on your system, including
> python3-dnf , to a version that contains a backport of the upstream
> DNF fix, then your current livecd-tools package will start working.

Thanks for the info. I must have misread as the github stuff I was looking at was an update to fs.py in livecd-tools.

This begs the question, how many devs does it take to fix bug (kinda like the lightbulb joke), but I'm not complaining... this is really a luxury.

Neal, thanks for filing the dnf ticket.  I hadn't gotten around to it yet.

TYL,
Scott Dowdle, x3931, BH262, ***@***.***

**Comment by Shadok** [comment] 2023-01-06 16:35
Hello,

Same issue here on AlmaLinux 8.6.
Issue seems to be fixed on the bugzilla report by using the dnf related package from Alma 8.7, but i have the latest packages from Alma 8.7 repo and it doesn't help at all, any idea ?

# rpm -qa |grep dnf
python3-libdnf-0.63.0-11.1.el8.alma.x86_64
dnf-data-4.7.0-11.el8.alma.noarch
dnf-4.7.0-11.el8.alma.noarch
libdnf-0.63.0-11.1.el8.alma.x86_64
python3-dnf-plugins-core-4.0.21-14.1.el8.noarch
dnf-plugins-core-4.0.21-14.1.el8.noarch
dnf-automatic-4.7.0-11.el8.alma.noarch
python3-dnf-4.7.0-11.el8.alma.noarch

**Comment by dowdle** [comment] 2023-01-06 17:04
Actually, livecd-creator has been working fine for me with the release of EL 8.7.

**Comment by Shadok** [comment] 2023-01-06 17:49
Damn :(
Could it be related to my ks file ?

I'll post it on monday if needed. I'm just creating a cli livecd with our backup solution package (networker) so i can restore if the os is down, so it's nothing big or extravagant.

In the meantime, could you post yours so i have some materiels to compare with ?

**Comment by dowdle** [comment] 2023-01-06 20:31
My build stuff is here: http://img.cs.montana.edu/linux/montanalinux/config/a8/

What is your build host running?  I always use the same distro I'm building with it... so AlmaLinux 8.7 for buiding AlmaLinux 8.7 live remixes.

**Comment by Shadok** [comment] 2023-01-06 20:39
Thanks, :) I'll take a look at it.
I'm running Alma 8.7 too and the ks was initially used, and working with Centos 7,so maybe I missed something with causes this.

**Comment by Shadok** [comment] 2023-01-09 08:33
I don't see anything problematic with my ks.

```
lang en_US.UTF-8
keyboard fr-latin9
timezone Europe/Paris
auth --useshadow --passalgo=sha512
bootloader --append="net.ifnames=0"
selinux --disabled
firewall --disabled
part / --size 8192 --fstype ext4
network --bootproto=dhcp --device=link --onboot=off --noipv6 --activate
services --enabled="sshd,NetworkManager"

# Accept license
eula --agreed

# Root password
rootpw --plaintext "root"

# Repo
%include repos.txt

%packages --ignoremissing
@include packages.txt
%end

%post --nochroot
# Copy needed files
cp -aR src/root/* $INSTALL_ROOT/
#chmod +x $INSTALL_ROOT/usr/local/sbin/init_liveos.sh
%end

%post
# disabling networker auto-start
/sbin/chkconfig networker off

# enable tmpfs for /tmp
systemctl enable tmp.mount

# Removing centos repositories
rm -f /etc/yum.repos.d/*.repo

# Fixing default locale to fr
localectl set-keymap fr
localectl set-x11-keymap fr

# Emptying root password, damned qwerty keyboard ...
passwd -d root

%end
```

**Comment by Shadok** [comment] 2023-01-09 08:38
I'm wondering if the EFI issue might be in cause :
```
Missing EFI file (/boot/efi/EFI/*/shimx64.efi)
Missing EFI file (/boot/efi/EFI/*/gcdx64.efi)
Failed to copy EFI files, no EFI Support will be included.
Missing initial EFI bootloader, skipping efiboot.img creation.
usage: mkefiboot [-h] [--debug] [-d] [-a] [-l LABEL] [-i ICONFILE]
                 [-n DISKNAME] [-p PRODUCT]
                 EFIBOOTDIR OUTPUTFILE
mkefiboot: error: /opt/livecd/tmp/imgcreate-yt1c4t_4/iso-6muuwz3m/EFI/BOOT is not a directory
```

**Comment by Shadok** [comment] 2023-01-09 09:31
I'm relieved i'm not alone fighting this : https://bytemeta.vip/repo/livecd-tools/livecd-tools/issues/243

The mentionned fix, adding -R to umount, line 1062 of python3-imgcreate's fs.py doesn't help :(
From : rc = call(['umount', self.dest])
To : rc = call(['umount','-R', self.dest])

**Comment by lersek** [comment] 2023-01-09 12:31
As of `dnf-4.7.0-10.el8`, you should have the fix for the original issue.

The original issue was a leak of libsolv's file descriptors:

~~~
COMMAND  PID USER FD  TYPE DEVICE SIZE/OFF   NODE NAME
python3 6500 root  7r  REG    8,1 25320727 395438 /var/tmp/imgcreate-mytcghah/install_root/var/cache/dnf/fedora.solv (deleted)
python3 6500 root  8r  REG    8,1 52531426 395450 /var/tmp/imgcreate-mytcghah/install_root/var/cache/dnf/fedora-filenames.solvx
~~~

This is something new now. `ks-script-*` is created by `imgcreate/creator.py` (i.e., livecd-tools itself). Regarding `libnss_files-2.28.so`, that bears a resemblance to commits 4dcf44f85207 and 4afde9352e82. I suggest filing a new (separate) ticket. Thanks.

**Comment by lersek** [comment] 2023-01-09 13:14
BTW I think this ticket should be closed now, per @dowdle's [comment](https://github.com/livecd-tools/livecd-tools/issues/232#issuecomment-1373899898).

**Closed** 2023-01-09 13:19 UTC
