### ISSUE TITLE
live-iso-to-disk fails when using dumpet to dump the boot image

### ISSUE THREAD

**Issue by AlexShinkin** [livecd-tools/livecd-tools#64] opened 2017-05-15 03:45 UTC
Observed in Fedora 25  x86_64 . The dumpet utility creates file named $SRC.0  instead of documented $SRC.1 , so the process stops with a message :

Dumping boot image to "whatever.iso.0"
mount:  whatever.iso.1: failed to setup loop device: No such file or directory

**Comment by Conan-Kudo** [comment] 2017-05-17 03:08
@AlexShinkin What version are you using? 24.4 is in updates-testing in Fedora 25...

**Comment by FGrose** [comment] 2017-11-04 17:43
I fail to reproduce this issue with Fedora-Workstation-Live-x86_64-25-1.3.iso
`sha256sum`
 818017f42a2741cfaf20e94aecf6a63d1b995abfdaff5917df7218d0d89976a7

`dumpet -i <path to>Fedora-Workstation-Live-x86_64-25-1.3.iso -d`
produced 3 files, one for each of the partitions. SRC.1 was mountable and contained the /EFI/BOOT/ directory.  The SRC.iso also contains the /BOOT/EFI/ directory with the appropriate files, so dumpet should have never been called.

I suspect that the downloaded source was incomplete and the --noverify option was used so that the livecd-iso-to-disk script did not verify the integrity of the source.

**Comment by Conan-Kudo** [comment] 2019-02-04 02:15
I can't reproduce this either. Closing.

**Closed by Conan-Kudo** 2019-02-04 02:15 UTC
